config/routes.rb
Rails.application.routes.draw do
  get 'restauraunts/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :restaurants
  get '/restaurants', to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :restaurant
  validates :restaurant, presence: true
  has_ancestry

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :comments

  def to_s
    name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar foundation-bar" data-topbar>
      <ul class="title-area">
        <li class='name'>
          <h1><%= link_to 'Reilly Restaurants', '#' %></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li>
            <%= link_to 'manage restaurants', '/admin' %>
          </li>
        </ul>
      </section>
    </nav>
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant, restaurant_path(restaurant) %>
    </li>
  <% end %>
</ul>